INSERT INTO REGION (name) VALUES ('center');
INSERT INTO REGION (name) VALUES ('kalamaria');
INSERT INTO REGION (name) VALUES ('pylaia');
INSERT INTO REGION (name) VALUES ('evosmos');
INSERT INTO REGION (name) VALUES ('oraiokastro');
INSERT INTO REGION (name) VALUES ('thermi');
INSERT INTO REGION (name) VALUES ('neapoli');

INSERT INTO BUILDING_TYPE (name) VALUES ('studios');
INSERT INTO BUILDING_TYPE (name) VALUES ('flat');
INSERT INTO BUILDING_TYPE (name) VALUES ('house');

INSERT INTO TRANSACTION_TYPE (name) VALUES ('buy');
INSERT INTO TRANSACTION_TYPE(name) VALUES ('rent');
INSERT INTO TRANSACTION_TYPE (name) VALUES ('sell');

INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',2,'yes','petrol',100000,'yes',20,1995,1,1,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',5,'yes','petrol',120000,'yes',32,1994,1,1,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',3,'no','gas',120000,'yes',32,1992,1,1,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',1,'yes','gas',200000,'no',40,1987,2,1,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',1,'no','gas',140000,'yes',35,1999,2,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',2,'yes','petrol',210000,'no',42,1991,2,2,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',4,'yes','gas',110000,'yes',30,1990,3,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',7,'no','gas',80000,'no',25,1993,3,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',1,'yes','petrol',295000,'yes',50,1999,3,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',5,'yes','gas',300000,'no',60,1989,4,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',1,'yes','petrol',190000,'yes',48,1989,4,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',6,'no','gas',220000,'yes',45,1988,4,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',2,'no','gas',340000,'yes',70,1986,5,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',3,'no','gas',245000,'yes',48,1989,5,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',2,'no','petrol',215000,'yes',32,2000,5,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',3,'no','gas',90000,'yes',25,1994,6,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',1,'no','gas',150000,'no',32,1995,6,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',7,'yes','petrol',160000,'yes',30,1995,6,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',5,'no','gas',205000,'yes',34,1996,7,1,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',1,'yes','gas',210000,'no',30,1996,7,1,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',6,'no','petrol',120000,'yes',40,1996,7,1,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',2,'no','gas',130000,'no',36,1991,5,1,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',3,'yes','gas',130000,'yes',50,1992,2,1,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',4,'yes','petrol',200000,'no',90,1992,1,1,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',4,'no','petrol',90000,'no',20,2004,4,1,3);

INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',1,'no','petrol',400,'yes',100,2004,1,2,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',2,'yes','petrol',102,'yes',200,1999,1,2,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',3,'yes','petrol',250,'no',300,1993,2,2,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',4,'no','petrol',500,'yes',320,1992,2,2,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',5,'yes','gas',700,'yes',180,2000,3,2,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',6,'yes','petrol',440,'no',50,2001,3,2,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',7,'yes','gas',340,'no',60,1990,4,2,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',1,'no','petrol',390,'no',31,1998,4,2,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',2,'no','gas',320,'no',70,1989,5,2,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',3,'yes','gas',280,'yes',115,2005,5,2,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',4,'yes','petrol',395,'yes',95,2000,6,2,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',5,'no','gas',245,'no',86,1996,6,2,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',6,'no','gas',490,'no',75,1997,7,2,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',7,'no','gas',600,'yes',63,1999,7,2,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',8,'no','petrol',270,'no',39,2000,1,2,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',1,'yes','petrol',1080,'yes',44,2010,1,2,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',2,'no','petrol',580,'no',56,2002,2,2,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',3,'yes','gas',310,'yes',46,2007,2,2,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',4,'yes','petrol',475,'no',68,1986,3,2,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',5,'yes','petrol',395,'yes',57,2011,3,2,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',6,'yes','gas',600,'no',79,1986,4,2,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',7,'yes','petrol',340,'yes',102,1988,4,2,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('yes',9,'no','gas',280,'yes',47,2000,5,2,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',8,'no','petrol',380,'yes',32,1999,5,2,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, region_id, transaction_type_id, type_id) VALUES ('no',1,'yes','gas',440,'no',32,1995,6,2,1);