INSERT INTO REGION (name) VALUES ('Center');
INSERT INTO REGION (name) VALUES ('Kalamaria');
INSERT INTO REGION (name) VALUES ('Pylaia');
INSERT INTO REGION (name) VALUES ('Evosmos');
INSERT INTO REGION (name) VALUES ('Oraiokastro');
INSERT INTO REGION (name) VALUES ('Thermi');
INSERT INTO REGION (name) VALUES ('Neapoli');

INSERT INTO BUILDING_TYPE (name) VALUES ('studios');
INSERT INTO BUILDING_TYPE (name) VALUES ('flat');
INSERT INTO BUILDING_TYPE (name) VALUES ('house');

INSERT INTO TRANSACTION_TYPE (name) VALUES ('buy');
INSERT INTO TRANSACTION_TYPE(name) VALUES ('rent');
INSERT INTO TRANSACTION_TYPE (name) VALUES ('sell');

INSERT INTO PHOTO (path) VALUES ('/photos/studio/1.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/studio/2.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/studio/3.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/studio/4.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/studio/5.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/studio/6.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/studio/7.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/studio/8.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/studio/9.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/studio/10.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/studio/11.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/studio/12.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/studio/13.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/1.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/2.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/3.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/4.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/5.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/6.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/7.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/8.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/9.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/10.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/11.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/12.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/13.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/14.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/15.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/16.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/17.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/18.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/19.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/20.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/21.jpg');
INSERT INTO PHOTO (path) VALUES ('/photos/flat/22.jpg');
INSERT INTO PHOTO (path) VALUES('/photos/house/1.jpg');
INSERT INTO PHOTO (path) VALUES('/photos/house/2.jpg');
INSERT INTO PHOTO (path) VALUES('/photos/house/3.jpg');
INSERT INTO PHOTO (path) VALUES('/photos/house/4.jpg');
INSERT INTO PHOTO (path) VALUES('/photos/house/5.jpg');
INSERT INTO PHOTO (path) VALUES('/photos/house/6.jpg');
INSERT INTO PHOTO (path) VALUES('/photos/house/7.jpg');
INSERT INTO PHOTO (path) VALUES('/photos/house/8.jpg');
INSERT INTO PHOTO (path) VALUES('/photos/house/9.jpg');
INSERT INTO PHOTO (path) VALUES('/photos/house/10.jpg');
INSERT INTO PHOTO (path) VALUES('/photos/house/11.jpg');
INSERT INTO PHOTO (path) VALUES('/photos/house/12.jpg');
INSERT INTO PHOTO (path) VALUES('/photos/house/13.jpg');
INSERT INTO PHOTO (path) VALUES('/photos/house/14.jpg');
INSERT INTO PHOTO (path) VALUES('/photos/house/15.jpg');




INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',2,'yes','petrol',100000,'yes',20,1995,1,1,1,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',5,'yes','petrol',120000,'yes',32,1994,2,1,1,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',3,'no','gas',120000,'yes',32,1992,3,1,1,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',1,'yes','gas',200000,'no',40,1987,4,2,1,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',1,'no','gas',140000,'yes',35,1999,14,2,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',2,'yes','petrol',210000,'no',42,1991,15,2,2,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',4,'yes','gas',110000,'yes',30,1990,16,3,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',7,'no','gas',80000,'no',25,1993,17,3,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',1,'yes','petrol',295000,'yes',50,1999,18,3,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',5,'yes','gas',300000,'no',60,1989,19,4,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',1,'yes','petrol',190000,'yes',48,1989,20,4,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',6,'no','gas',220000,'yes',45,1988,21,4,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',2,'no','gas',340000,'yes',70,1986,22,5,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',3,'no','gas',245000,'yes',48,1989,23,5,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',2,'no','petrol',215000,'yes',32,2000,24,5,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',3,'no','gas',90000,'yes',25,1994,25,6,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',1,'no','gas',150000,'no',32,1995,26,6,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',7,'yes','petrol',160000,'yes',30,1995,27,6,1,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',5,'no','gas',205000,'yes',34,1996,36,7,1,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',1,'yes','gas',210000,'no',30,1996,37,7,1,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',6,'no','petrol',120000,'yes',40,1996,38,7,1,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',2,'no','gas',130000,'no',36,1991,39,5,1,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',3,'yes','gas',130000,'yes',50,1992,40,2,1,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',4,'yes','petrol',200000,'no',90,1992,41,1,1,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',4,'no','petrol',90000,'no',20,2004,42,4,1,3);

INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',1,'no','petrol',400,'yes',100,2004,5,1,2,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',2,'yes','petrol',102,'yes',200,1999,6,1,2,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',3,'yes','petrol',250,'no',300,1993,7,2,2,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',4,'no','petrol',500,'yes',320,1992,8,2,2,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',5,'yes','gas',700,'yes',180,2000,28,3,2,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',6,'yes','petrol',440,'no',50,2001,29,3,2,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',7,'yes','gas',340,'no',60,1990,30,4,2,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',1,'no','petrol',390,'no',31,1998,31,4,2,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',2,'no','gas',320,'no',70,1989,43,5,2,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',3,'yes','gas',280,'yes',115,2005,44,5,2,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',4,'yes','petrol',395,'yes',95,2000,45,6,2,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',5,'no','gas',245,'no',86,1996,46,6,2,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',6,'no','gas',490,'no',75,1997,9,7,2,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',7,'no','gas',600,'yes',63,1999,10,7,2,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',8,'no','petrol',270,'no',39,2000,11,1,2,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',1,'yes','petrol',1080,'yes',44,2010,12,1,2,1);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',2,'no','petrol',580,'no',56,2002,32,2,2,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',3,'yes','gas',310,'yes',46,2007,33,2,2,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',4,'yes','petrol',475,'no',68,1986,34,3,2,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',5,'yes','petrol',395,'yes',57,2011,35,3,2,2);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',6,'yes','gas',600,'no',79,1986,47,4,2,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',7,'yes','petrol',340,'yes',102,1988,48,4,2,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('yes',9,'no','gas',280,'yes',47,2000,49,5,2,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',8,'no','petrol',380,'yes',32,1999,50,5,2,3);
INSERT INTO BUILDING (elevator, floor, furnished, heating, price, renovated, square_meters, year, photo_id, region_id, transaction_type_id, type_id) VALUES ('no',1,'yes','gas',440,'no',32,1995,13,6,2,1);